#' Perspective projection to obtain simplex
#'
#' This function reduces data dimension by loading matrix and then project
#' dimension-reduced data to the hyperplane orthogonal to c(1,0,...,0),
#' i.e., the first axis in the new coordinate system..
#' @param data Each row is a gene and each column is a sample. Missing values are not supported.
#' @param W The matrix whose rows are loading vectors;
#' should be obtained from \code{\link{CAM}}/\code{\link{CAMPrep}} function.
#' @details This function can project gene expression vectors to simplex plot
#' generated by \code{\link{CAM}}/\code{\link{CAMPrep}}. \code{Xproj} in
#' "CAMPrepObj" only contains the simplex of genes after filtering.
#' This function can help oberve all genes in simplex plot.
#' @return  The data after Perspective projection.
#' @export
#' @examples
#' #obtain data
#' data(ratMix3)
#' data <- ratMix3$X
#'
#' #obtain simplex
#' Xproj <- XWProj(data, rCAM$PrepResult$W)
#'
#' #plot simplex in 3d space
#' library(rgl)
#' plot3d(Xproj[,-1]) #The first dimension is constant after projection
XWProj <- function(data, W){
    Xp <- data %*% t(W)

    L <- nrow(W)
    Xcenter <- c(1, rep(0, L-1))
    Xp / c(Xp %*% Xcenter)
}
